### ISSUE TITLE
Gnome Settings -> System Info: Korora icon missing

### ISSUE THREAD

**Issue by FlorianWilhelm** [kororaproject/kp-korora-settings-gnome#6]
In the gnome settings under details/info it seems that the Korora Icon is missing since only a small square with a question mark is displayed. You can directly access this  settings submenue with `gnome-control-center info`.  On the upper right side of the panel it says "Korora 23" and above it only the aforementioned square is displayed. Looks like a missing icon or link to a resource for me.

**Comment by spariant** [comment]
+1  I can replicate this issue in korora 23 gnome. 
Missing or renamed icon image file, looks like.

**Comment by csmart** [comment]
Thanks, I expect this is the same as kororaproject/kp-korora-logos#2 but I don't know what icon is meant to be there.

**Comment by spariant** [comment]
There are logo files in /usr/share/pixmaps. Perhaps fedora-logo.png (attached) or fedora-logo-white.png?
![fedora-logo](https://cloud.githubusercontent.com/assets/18563394/14963801/ab4a9a22-10a5-11e6-8af5-3dc661cd5fd5.png)

**Comment by csmart** [comment]
@spariant thanks, although that logo is already there, so if that was the one it wanted it should already work. Presumably the settings screen is looking for a specific logo somewhere that doesn't exist on our korora systems for some reason. That's the bit I don't know - what log is it looking for.

I can't even tell with an strace :-(

**Comment by csmart** [comment]
@lithrem found the answer by looking at control-center source code, it's looking for /usr/share/pixmaps/fedora-logo-icon.png which we don't ship (being based off generic-logos). I'll have to update korora-logos with this file. Thanks.

**Comment by FlorianWilhelm** [comment]
Well, it seems this issue is actually fixed judging from @csmart's last post. I'll close it.
